### ISSUE TITLE
improve font providers

### ISSUE THREAD

**Issue by danielroe** [nuxt/fonts#10]
each provider supports some very interesting things, including axes for variable fonts, that we are not always taking advantage of.

would be nice to:
* support passing options to a provider (e.g. google can accept a `text` option to refine the subset)
* look at and improve google, fontshare, bunny providers

**Comment by qwerzl** [comment]
@danielroe I'm wondering how we should provide support for variable fonts. AFAIK some of our providers eg. `adobe` doesn't support variable fonts, so how should we deal with these providers if `default.weight` is defined as a string in config? Should we just disable the unsupported providers in such cases?

**Comment by danielroe** [comment]
closing as it's a bit broad

specific issues can be raised in https://github.com/unjs/unifont
