### ISSUE TITLE
Adobe font provider does not support dynamic subset

### ISSUE THREAD

**Issue by dungsil** [nuxt/fonts#105]
`@nuxt/font` is fetching CSS files from Adobe Typekit. However, for fonts with East Asian languages, it is unable to fetch the CSS extensions.

https://github.com/nuxt/fonts/blob/22ae0b124095a8381971d1bf531ceff3eed53024/src/providers/adobe.ts#L109

Below is the difference in the Adobe fonts screen:

Inter Variable ( css file include )
![image](https://github.com/nuxt/fonts/assets/39783731/7ef51804-e0cc-41a4-9d3b-a8457ac1c2fc)

Pretendard ( javascript file include )
![image](https://github.com/nuxt/fonts/assets/39783731/291af576-0e9a-4553-bb2f-a73838da388c)

East Asian characters (especially CJK) seem to have a large size, so Adobe can't import the entire font by default or all characters. 
![image](https://github.com/nuxt/fonts/assets/39783731/5d99a950-f998-4fc8-99ec-29422ea2918c)

If you look at the actual API being called, you'll see that East Asian languages don't come with css files.
 - [dpj7fny.js](https://use.typekit.net/dpj7fny.js) - a js file is output
 - [dpj7fny.css](https://use.typekit.net/dpj7fny.css) - 412 precondition failed

Can you add support for these areas? 
If not, you can update the documentation to avoid confusing Asian users.

In the logs, it looks like this, making it difficult to determine the cause.
![image](https://github.com/nuxt/fonts/assets/39783731/06387ac8-77c1-4444-8736-db42bd27ab24)

Reference:
1. Adobe fonts docs: https://helpx.adobe.com/kr/fonts/using/dynamic-subsetting.html
2. Test font (Pretendard): https://fonts.adobe.com/fonts/pretendard

**Comment by qwerzl** [comment]
This is tricky - adding support for east Asian characters is indeed possible, actually I've already figured out a bit, but I don't think Adobe will be happy with this as the code they provide is clearly obfuscated and is not documented anywhere. So I guess we should just add a note in the docs to either directly use the script or use the local provider in such cases. @danielroe What do you think?
