### ISSUE TITLE
This font won't work on production: DM Serif Display

### ISSUE THREAD

**Issue by fayazara** [nuxt/fonts#122]
Thought this issue was related to my project, but I was able to reproduce it, sounds weird but this font won't work on a production build - https://fonts.google.com/specimen/DM+Serif+Display

I am using the font by mentioning it in my tailwind config 

```ts
import type { Config } from "tailwindcss";

export default <Partial<Config>>{
  theme: {
    fontFamily: {
      sans: [
        "DM Sans",
        "Avenir Next",
        "Roboto",
        "-apple-system",
        "BlinkMacSystemFont",
        '"Segoe UI"',
        "Ubuntu",
        '"Helvetica Neue"',
        "Arial",
        '"Noto Sans"',
        "sans-serif",
        '"Apple Color Emoji"',
        '"Segoe UI Emoji"',
        '"Segoe UI Symbol"',
        '"Noto Color Emoji"',
      ],
      mono: [
        "Cascadia Code",
        "ui-monospace",
        "SFMono-Regular",
        "Menlo",
        "Monaco",
        "Consolas",
        "Liberation Mono",
        "Courier New",
        "monospace",
      ],
      display: ["DM Serif Display", "Inter", "sans-serif"],
    },
  },
  plugins: [require("@tailwindcss/typography")],
};
```

The first font `DM Sans` is loads correctly, but the display font wont, throws a 404 in production.

Here's a reproduction - https://github.com/fayazara/nuxt-font-repro

Dev environment screenshot 
![Screenshot 15-04 at 19](https://github.com/nuxt/fonts/assets/15716057/03183b9a-0231-4b90-9522-3b4a8f32d8bb)

Production screenshot
![Screenshot 15-04 at 19](https://github.com/nuxt/fonts/assets/15716057/33542759-acd4-42c7-bfe9-030d7812f10c)

**Comment by fayazara** [comment]
@danielroe Can we use this module as edge version (latest commit) till a new release it cut.

**Comment by danielroe** [comment]
I'll release ❤️
