### ISSUE TITLE
Add support for Google Material Symbols

### ISSUE THREAD

**Issue by AndersCV** [nuxt/fonts#127]
Currently it is not possible to use google as a provider for Material Symbols. 

Looking at the current implementation of the google provider it seems it's only looking at the meta data for fonts found at: https://fonts.google.com/metadata/fonts 

![Uploading image.png…]()

Metadata for googles Material Symbols can be found at https://fonts.google.com/metadata/icons

**Comment by qwerzl** [comment]
Icon's metadata is in a completely different format than Fonts, so we might need to create a new provider for that. @danielroe What do you think?

Meanwhile, you could always use the material symbols provided by the `fontsource` provider.

**Comment by AndersCV** [comment]
@qwerzl Thanks for the response and suggetions. I thought the same but unfortunately Material Symbols provided by google is not totally identical to that of fontsource which is blocking us from changing. 

As a workaround I'll try and create my own custom provider for Google Material Symbols, however I do think this module should support it out of the box.
