### ISSUE TITLE
Allow downloading priority by extensions

### ISSUE THREAD

**Issue by Schllimazll** [nuxt/fonts#135]
Is it possible to specify the priority of downloading files by their extension (woff 2, woff, tff)? Now, if a folder contains both ttf and woff2 at the same time, then the module loads tff. Or do I only need to store fonts in woff2 format?

![image](https://github.com/nuxt/fonts/assets/72357875/08da9424-f02a-4016-9d33-654249fee638)
![image](https://github.com/nuxt/fonts/assets/72357875/7fa7c6ad-3199-4309-b06b-443b59924ef8)

**Comment by JorgeO3** [comment]
Any updates on this?
