### ISSUE TITLE
woff2 should be first in local fonts

### ISSUE THREAD

**Issue by Grebady** [nuxt/fonts#167]
When ttf, woff, woff2 files are used, in the resulting css woff2 files should be generated in the first place. Now they are generated for the last. example
@font-face{font-family:Mont;src:url(../fonts/Mont/Mont-100.ttf) format(truetype),url(../fonts/Mont/Mont-100.woff) format(woff),url(../fonts/Mont/Mont-100.woff2) format(woff2);font-display:swap;font-weight:100;font-style:normal}

**Comment by qwerzl** [comment]
Duplication of #135. Closing this issue.
