### ISSUE TITLE
Font not loading when upgrading to nuxt 3.12.1 and enabling `compatibilityVersion: 4`

### ISSUE THREAD

**Issue by JulianDueck** [nuxt/fonts#176]
Hello.
I upgraded my project to nuxt 3.12.1 with `npx nuxi@latest upgrade --force`.
Enabled this flag in `nuxt.config.ts`
```
export default defineNuxtConfig({
  future: {
    compatibilityVersion: 4,
  },
})
```
Restructured my projects file structure following [this guide](https://nuxt.com/docs/getting-started/upgrade#new-directory-structure).
My app functions like before, only that my custom font is not loading. I have a .woff font in `public/` folder, but nuxt is not using it for some reason. Before the changes I made, it worked just fine.
I'm using nuxt/fonts 0.7.0

**Comment by oritwoen** [comment]
I have the same error. But it only occurs in my development environment. Once built, everything works fine.

The path `/_fonts/*` returns endpoint 404 to dev.

![Zrzut ekranu z 2024-07-02 18-41-54](https://github.com/nuxt/fonts/assets/18102267/072497d7-0550-416d-9602-c79690d04464)

**Comment by vptill** [comment]
It never worked for me in development mode, however, after updating to 3.12.1, it won't load in production either.
