### ISSUE TITLE
Adobe doesn't load

### ISSUE THREAD

**Issue by MarcoTroost** [nuxt/fonts#187]
Hi guys,

This package seems just what my project needs! 

Unfortunately, adobe fonts do no load. 
N.B> Adobe doesn't load in the playground either...

Hope it will be sorted,

kind regards,

Marco

**Comment by danielroe** [comment]
Would you provide a reproduction? Unfortunately Stackblitz does not always work due to CORS.

**Comment by MarcoTroost** [comment]
Hi Daniel, thank you for the swift reply & you great work on Nuxt!

A reproduction (on stackblitz) would probably also cause CORS issues. 
I have used the fonts module on my testdomain though. You can find it @ www.trauminfo.de 

_This is my nuxt.config.ts:_

```
export default defineNuxtConfig({
  app: {
    head: {
      htmlAttrs: {
        lang: 'nl'
      }
    }
  },
  site: {
    url: 'https://www.trauminfo.de',
    name: 'Droominfo.nl',
    defaultLocale: 'nl'
  },
  nitro: {
    moduleSideEffects: [
      '@material/web/tabs/tabs.js',
      '@material/web/tabs/primary-tab.js',
      '@material/web/textfield/filled-text-field.js',
      '@material/web/textfield/outlined-text-field.js',
      '@material/web/button/filled-button.js',
      '@material/web/button/outlined-button.js',
      '@material/web/ripple/ripple.js',
      '@material/web/icon/icon.js',
    ],
  },
  modules: [
    ["nuxt-ssr-lit", { litElementPrefix: ["md-"] }],
    '@nuxtjs/tailwindcss',
    '@vueuse/nuxt',
    'nuxt-lodash',
    "@nuxtjs/sitemap",
    "@nuxtjs/google-adsense",
    "@nuxt/fonts"
  ],
  fonts: {
    adobe: {
      id: ['ddx0usu'],
    },
    experimental: {
      processCSSVariables: true
    }
  },
  googleAdsense: {
    id: 'ca-pub-7034225815334900',
    test: true
  },
  tailwindcss: {
    cssPath: '~/assets/css/droominfo.css',
    exposeConfig: false,
  },
  routeRules: {
    '/': { prerender: true },
  }
});
```

_Snippet from my tailwind.config:_

```
  theme: {
    extend: {
      fontFamily: {
        sans: ['ff-tisa-sans-web-pro', 'sans-serif'],
        serif: ['ff-tisa-web-pro', 'serif'],
      },
```

_Example implementation:_

`<p class="font-sans mb-4 text-blue-600 ...">`


N.B. This is the correct project id (ddx0usu), since this works on my main domain @ www.droominfo.nl

kind regards,

Marco Troost

**Comment by qwerzl** [comment]
> _Snippet from my tailwind.config:_
> 
> ```
>   theme: {
>     extend: {
>       fontFamily: {
>         sans: ['ff-tisa-sans-web-pro', 'sans-serif'],
>         serif: ['ff-tisa-web-pro', 'serif'],
>       },
> ```

We only match the names of fonts. `ff-tisa-sans-web-pro` is a slug, so it won't be matched. You could try using `FF Tisa Sans Pro` and see how it goes.

**Comment by MarcoTroost** [comment]
Hi Qwerzl,

I've tried `FF Tisa Sans Pro`, but this doesn't work either. 
N.B. The slug is the documented implementation as given by Adobe:

<img width="413" alt="Scherm­afbeelding 2024-07-01 om 08 39 46" src="https://github.com/nuxt/fonts/assets/16369103/b3167445-26c5-4879-b941-5021013a9b32">

When i look in the .nuxt folder, `nuxt-fonts-global.css `is empty:

<img width="549" alt="Scherm­afbeelding 2024-07-01 om 08 38 38" src="https://github.com/nuxt/fonts/assets/16369103/397e13ed-d8c0-4a86-820c-559ee8e3cadb">

Hope these screenshots are of help.

kind regards, Marco

**Comment by qwerzl** [comment]
Ah, I understand where the problem is. Currently we match fonts with its name from the Typekit API to check if it exists, then we fetch the CSS and get the `@font-face` definitions whose `family-name` is the font's slug. But for this font, its slug (`ff-tisa-web-pro`) and its font-family name defined in the CSS (`ff-tisa-web-pro`) are not the same.
