### ISSUE TITLE
Question: How to fetch only woff2 format?

### ISSUE THREAD

**Issue by lttr** [nuxt/fonts#195]
Since woff2 format is often enough, I would like to have woff2 and only woff2 format of a font downloaded. I have not found a way how to configure a provider like Google in order to force only this format.

## Details

I have tried the Fonts module both without any configuration and with configuration like this one:

```
  fonts: {
    families: [
      {
        name: "Poppins",
        weights: [400],
        styles: ["normal"],
        subsets: ["latin-ext", "latin"],
        provider: "google",
      },
    ],
  },
```

In both cases the behavior is following:
- on dev server both woff and woff2 formats are downloaded (woff first)
- on preview (nuxi preview) of a prod build (node preset) only the woff format is downloaded

I was unable to create a reproduction on Stackblitz since fonts are not at all downloaded there with Google provider.

**Comment by lttr** [comment]
While the bot might be right with the answer above, it misses the point. If I want I can use the URL directly or I might download the fonts manually. The advantage here is that this module could do it automatically.

**Comment by lttr** [comment]
> To configure the Fonts module to download only the woff2 format when using a provider like Google, you can specify the font data directly with the src property in the families array. 

It does not work since I need 2 different subsets as mentioned in a code snippet in the original description. @dosu

**Comment by neobutter** [comment]
@lttr 
I checked with Nuxt Devtools, 
For woff2 there is a unicode-range, but for woff there is no unicode-range.

In this case, the browser seems to be downloading woff.

**Comment by lttr** [comment]
> @lttr I checked with Nuxt Devtools, For woff2 there is a unicode-range, but for woff there is no unicode-range.
> 
> In this case, the browser seems to be downloading woff.

@neobutter Can you elaborate on this? I don't really understand how to workaround this.

I'm not interested in woff at all, browsers support woff2 just fine. I would even welcome a switch in the nuxt/fonts module to completely disable all formats other than woff2.

**Comment by neobutter** [comment]
@lttr You've created a new [issue](https://github.com/nuxt/fonts/issues/204).

**Comment by danielroe** [comment]
let's track in https://github.com/nuxt/fonts/issues/204.
