### ISSUE TITLE
Problems with Adobe as provider

### ISSUE THREAD

**Issue by towa-gregoryHa** [nuxt/fonts#221]
Hello,

I have problems using nuxt fonts with Adobe as Provider (and tailwind for css)

----

This ist the font I want to use and what postman shows me for the correct names:

```
"families": [
            {
                "id": "some id",
                "name": "DIN 2014",
                "slug": "din-2014",
                "css_names": [
                    "din-2014"
                ],
                "css_stack": "\"din-2014\",sans-serif",
                "variations": [
                    "n4",
                    "n6",
                    "n7"
                ]
            }
        ]
    }
```

----

This is how my tailwind.config.ts looks:

```
fontFamily: {
    custom: ['din-2014', 'sans-serif'],
},
```

This is how my nuxt.config.ts looks:

```
fonts: {
    families: [{ name: 'din-2014', provider: 'adobe' }],
    adobe: {
      id: ['some id'],
    },
    defaults: {
      weights: [400],
      styles: ['normal', 'italic'],
      subsets: [
        'cyrillic-ext',
        'cyrillic',
        'greek-ext',
        'greek',
        'vietnamese',
        'latin-ext',
        'latin',
      ],
      fallbacks: {
        monospace: ['Tahoma'],
      },
    },
  },
```

----

I get this warning with the above code:

![Bildschirmfoto 2024-08-14 um 09 26 04](https://github.com/user-attachments/assets/7987dfd9-7c5c-4e29-b98d-f57d24f15d11)

----

I also tried other names like: "DIN 2014" or "Din 2014", but it seems like the font does not get through to the frontend of my nuxt application. 

PS: If I use the adobe cdn link everything works fine

Thank you for the help!

newbie

**Comment by qwerzl** [comment]
Please provide a reproduction. "DIN 2014" should be the right name in theory.

**Comment by towa-gregoryHa** [comment]
Could there be a "reading problem" because in the tailwind config it is: 

```
fontFamily: {
    custom: ['din-2014', 'sans-serif'],
},
```

and in the nuxt config it is "DIN 2014"

so:

`din-2014` is not equal to `DIN 2014`

**Comment by towa-gregoryHa** [comment]
I also get this msg:

<img width="525" alt="Bildschirmfoto 2024-08-19 um 11 10 11" src="https://github.com/user-attachments/assets/2741d3fc-4602-4af4-a4fb-127537a68cff">

**Comment by towa-gregoryHa** [comment]
When I set **global** to true, I get at least the font face declarations injected into the `nuxt-fonts-global.css`

`families: [{ name: 'DIN 2014', provider: 'adobe', global: true }],`

Then I can via my `main.scss` add the DIN 2014 font to the "project" and access it.

```
@tailwind base;

@layer base {
  /*! purgecss start ignore */
  html {
    font-size: 1em;
    font-family: 'DIN 2014', system-ui, sans-serif;
  }
}

/*! purgecss end ignore */
```


But the "tailwind wiring" is still not working!

Any ideas?

**Comment by towa-gregoryHa** [comment]
We solved it by using this in the tailwind.config.ts

```
      fontFamily: {
        custom: ['"DIN 2014"', 'system-ui', 'sans-serif'],
      },
```

**Comment by qwerzl** [comment]
Glad you figured it out. As I said in the previous reply, "DIN 2014" should be the right name. Should I close the issue?

**Comment by towa-gregoryHa** [comment]
Hi qwerzl, yes you can close it of course. But I would mention this somewhere in the docs maybe, because it is a bit tricky I think and you do not use it that way intuitively. (with the `'""'`)
