### ISSUE TITLE
cdnURL is not respected by google provider

### ISSUE THREAD

**Issue by haakonmt** [nuxt/fonts#224]
`app.cdnURL` (as the issue suggests) does not seem to be respected by the google provider, giving me 404s in production due to the font requests not being prepended correctly. Curiously, fonts provided by the local provider seem to be working as intended. I have not tried other providers, but as they look quite similar, I would presume this would also effect the other remote providers.

What makes it even more curious, is that if the fonts have already been cached (i.e. through a previous build), the paths _are_ generated correctly (prefixed by `cdnURL`).

**EDIT:** Ok, so the reason it works after the fonts have been cached is that the remote fonts are now picked up by the local provider (since they have been cached locally), and thus served correctly.

**Comment by danielroe** [comment]
possibly linked to https://github.com/nuxt/fonts/issues/242 - would value a reproduction so I can investigate further 🙏

**Comment by haakonmt** [comment]
@danielroe Still no dice on 0.9.1 it seems, I will try to provide a minimal reproduction when I have some spare time. Thanks for your effort. 🙌

**Comment by haakonmt** [comment]
@danielroe Interesting observation on 0.9.1: On the first build, the raw font-faces produced in the server bundle looks like this: 
```
@font-face {
  font-family: Inter;
  src: local("Inter Variable"), url(/_fonts/...);
  ...
}
```
On the second run (after the remote fonts have been cached), they look like this:
```
@font-face {
  font-family: Inter;
  src: local("Inter Variable"), url( publicAssetsURL("/_fonts/..."));
  ...
}
```

The `publicAssetsURL` helper seems to be doing what I need, it just isn't used on a clean build (which my CI builds are 😅).

**Comment by danielroe** [comment]
Oh, that’s weird. Maybe a race condition. Probably a simple fix if so! 🤞

**Comment by danielroe** [comment]
does it do this if you manually move them after the build, rather than using the nitro hook?

**Comment by haakonmt** [comment]
@danielroe I could probably have found a better way to illustrate the issue, but yeah. IRL we don't use a hook, and deploy the assets after the build is complete, and it still breaks.

**Comment by haakonmt** [comment]
@danielroe Works like a charm now, thans for the clever fix! 🙏
