### ISSUE TITLE
Why use public folder over assets folder

### ISSUE THREAD

**Issue by stijns96** [nuxt/fonts#231]
Hi there,

I'm wondering why @nuxt/fonts docs says that we have to store our local fonts inside the public folder while the [nuxt docs](https://nuxt.com/docs/guide/directory-structure/assets) says that fonts ate mostly stored in the assets folder.

Why is that and does the assets folder also works?

**Comment by danielroe** [comment]
The `~/assets` folder isn't a special folder as such - things in that folder only become part of your build if they are imported into your app. Fonts normally shouldn't be part of your build as they don't change per-build. Instead, it's better to keep only the fonts you use in your public folder.
