### ISSUE TITLE
wrong baseURL in inline CSS

### ISSUE THREAD

**Issue by JohnCampionJr** [nuxt/fonts#242]
Related to #96; this still is broken.

If I set `baseUrl` to `/subapp` then Nuxt Fonts uses a link like:

`http://localhost:5001/subapp/_fonts/rP2rp2ywxg089UriCZaSExd86J3t9jz86Mvy4qCRAL19DksVat9XCm3w-ByvzuLy2fa.woff`

However this results in a 404, but this link works (note no base url)
`http://localhost:5001/_fonts/rP2rp2ywxg089UriCZaSExd86J3t9jz86Mvy4qCRAL19DksVat9XCm3w-ByvzuLy2fa.woff`

**Comment by danielroe** [comment]
Resolved in v0.8.0.

**Comment by JohnCampionJr** [comment]
I'm not seeing a change in 0.8.0.  Same symptoms.  It's not the link to the font, it has the baseUrl. It is the actual location of the font file from the server

**Comment by danielroe** [comment]
@JohnCampionJr Would you be able to provide a reproduction? 🙏

**Comment by JohnCampionJr** [comment]
@danielroe 

[Reproduction](https://github.com/JohnCampionJr/nuxt-fonts-baseurl/tree/baseurl)

![image](https://github.com/user-attachments/assets/4e2e624d-ae24-4395-b01a-eeaca6330d6b)

Fonts are here though (and should not be)
http://localhost:3000/_fonts/rP2Yp2ywxg089UriI5-g4vlH9VoD8Cmcqbu0-K6z9mXg-VNw7NHvqnp.woff2

**Comment by danielroe** [comment]
@JohnCampionJr I believe this is an issue with prerendered pages only - can you confirm?

**Comment by JohnCampionJr** [comment]
@danielroe I'm not using prerendering in my main app that experiences this bug. 

Disabled this, no effect:
```
 routeRules: {
     // Temporary workaround for prerender regression. see https://github.com/nuxt/nuxt/issues/27490
     '/': { prerender: false }
   },
```

tried ```ssr:false```, no effect

**Comment by JohnCampionJr** [comment]
@danielroe  I'm sorry to report this, but the bug persists in v0.9.0.

<img width="961" alt="image" src="https://github.com/user-attachments/assets/9c0df1da-8fa2-490d-b0e9-535db002cd29">

**Comment by danielroe** [comment]
@JohnCampionJr I think I totally misunderstood your issue. So the baseURL is being correctly rendered but the fonts aren’t served there?

how are you running/deploying your built site? (Not with `nuxi preview` I trust?)

**Comment by JohnCampionJr** [comment]
That is correct.  I'm just using nuxt last dev server.  It's pretty easy to see the bug with the reproduction.  Just run it and look at the console.

**Comment by danielroe** [comment]
sorry for the back and forth on this one - I thought you were talking about _production_ CSS.

hopefully should be resolved in v0.9.1 🙏

**Comment by JohnCampionJr** [comment]
@danielroe confirming it is fixed - thank you so much!!!

**Comment by danielroe** [comment]
at last!! 🎉

**Comment by Jan-Heussner** [comment]
Sorry for writing in an closed ticket but it perfectly fits here.

What about the buildAssetsDir? When i run "npm run generate" the path does not contain the dir or is there another way to give a specific output path? (SSR:FALSE)
