### ISSUE TITLE
Issue loading certain fonts with Adobe Fonts (Typekit)

### ISSUE THREAD

**Issue by jackbarham** [nuxt/fonts#314]
I'm trying to load two different fonts from Adobe Fonts and it only loads one.

The fonts I'm trying to use:
- Transducer
- Articulat CF

Articulat CF does load but Transducer doesn't.

Here is my `nuxt.config.ts`:
```js
export default defineNuxtConfig({
  compatibilityDate: '2024-04-03',
  devtools: { 
    enabled: true 
  },
  modules: [
    '@nuxtjs/tailwindcss',
    'nuxt-svgo',
    '@nuxt/fonts',
  ],
  fonts: {
    adobe: {
      id: ['ztp5pvp'],
    },
    families: [
      { name: '"Articulat CF"', provider: 'adobe' },
      { name: '"Transducer"', provider: 'adobe' },
    ],
  },
  app: {
    //
  }
})
```

Here is my `tailwind.config.js`:
```js
module.exports = {
  theme: {
    extend: {
      colors: {
        'brand-primary': '#5122E1',
      },
      fontFamily: {
        transducer: ['"Transducer"', 'system-ui', 'sans-serif'],
        articulat: ['"Articulat CF"', 'system-ui', 'sans-serif'],
      },
      typography: {
        DEFAULT: {
          css: {
            'blockquote p:first-of-type::before': false,
            'blockquote p:first-of-type::after': false,
          },
        },
      },
    },
  },
  variants: {
    extend: {
      order: ['odd', 'even'],
      marginBottom: ['last'],
    }
  },
  plugins: [
    require('@tailwindcss/typography'),
    require('@tailwindcss/forms'),
  ],
}
```

Here's a screenshot for my Abode Font kit
![Image](https://github.com/user-attachments/assets/1fbc1817-9f8a-433c-b38c-9e2526e21c33)

This is the Adobe Fonts CSS: https://use.typekit.net/ztp5pvp.css.

I know you can't use the `'articulat-cf'` lowercase format, so I've tried `'"Transducer"'`, `'Transducer'`, `'"transducer"'`, and `"transducer"` formats both in `nuxt.config.ts` and `tailwind.config.js` which never loads that font, but loads and displays `"Articulat CF"` fine.

Am I missing something here?

Thanks.

**Comment by qwerzl** [comment]
Please confirm again whether you've added Transducer to the kit. Both the CSS and the metadata returned by adobe include only  `Articulat CF`.

**Comment by jackbarham** [comment]
Hey, @qwerzl. I think I briefly removed it to try other fonts, but it's back in again now: https://use.typekit.net/ztp5pvp.css. 

Thanks.

**Comment by qwerzl** [comment]
This is because you didn't choose `400` as weight in your kit for Transducer. Nuxt Fonts isn't capable of automatically detecting font weights yet. So by default, only weight `400` is downloaded unless it's a variable font. You'll need to configure the `weights` property manually in `families`.

**Comment by jackbarham** [comment]
Thank you for the response, @qwerzl. I've added Transducer 400 to the web kit, but it's unclear how to configure the weights. I didn't need to set them up for `Articulat CF`, which works as expected. 

How would I do this? I currently use `400`, `500`, `600`, and `900` for the Transducer font.

**Comment by qwerzl** [comment]
It's written in [the docs](https://fonts.nuxt.com/get-started/configuration#families). 

```typescript
  fonts: {
    families: [
      { name: 'Transducer', weights: [500, 600, 900] },
    ]
  }
```

**Comment by jackbarham** [comment]
I did try that, but it isn't working, so I thought I might have missed something. 

```js
fonts: {
  adobe: {
    id: ['ztp5pvp'],
  },
  families: [
    { name: '"Articulat CF"' },
    { name: '"Transducer"', weights: [400, 500, 600, 900] },
  ],
},
```

Heads up, I've tried other font packs with different Adobe Fonts, and so far, all the others seem to work. It's only Transducer I have an issue with.

**Comment by jackbarham** [comment]
I tried that, but I realised I was using `'"Transducer"'` in quotes. I removed the quotes on both files, and it's fixed now.

This is the final code that works if it helps anyone else.

`nuxt.config.ts`
```js
fonts: {
  adobe: {
    id: ['ztp5pvp'],
  },
  families: [
    { name: 'Transducer', weights: [400, 500, 900], styles: ['normal'] },
    { name: '"Articulat CF"', weights: [400, 800], styles: ['normal', 'italic'] },
  ],
},
```

`tailwind.config.js`
```js
fontFamily: {
  transducer: ['Transducer', 'system-ui', 'sans-serif'],
  articulat: ['"Articulat CF"', 'system-ui', 'sans-serif'],
},
```

Thanks again for your help 🙂
