### ISSUE TITLE
Nested CSS font-family not working as expected

### ISSUE THREAD

**Issue by onmax** [nuxt/fonts#371]
## Description

Using nuxt fonts to set different fonts for specific CSS classes works perfectly for single-level classes, but when trying to apply a font to nested CSS classes, it does not load as expected.

For example, Lato works fine for `.lato`, but Nunito fails to apply in nested elements like `.nunito p`:

```vue
<template>
  <div class="lato">
    'Lato works!'

    <div class="nunito">
      <p>'Nunito does not work :('</p>
    </div>
  </div>
</template>

<style scoped>
.lato {
  font-family: 'Lato';
}

.nunito {
  p {
    font-family: 'Nunito';
  }
}
</style>

```

## Reproduction steps

1. Apply a font family using nuxt fonts to a nested CSS class selector.

> Note that the font only applies to single-level selectors, not nested ones like `.nunito p`.

## Expected behaviour

Both fonts should be applied according to the CSS structure, with `Lato` on the outer `div` and `Nunito` on the inner `<p>` element.

## Reproduction link

[Stackblitz repro](https://stackblitz.com/edit/github-5srqpg?file=app.vue)

**Comment by onmax** [comment]
I assume that the AST does not run nested CSS [correctly here](https://github.com/nuxt/fonts/blob/9ae5780e4271bf2ad03f511c43d2ab5f600a7e24/src/plugins/transform.ts#L102-L136).

If it is ok, I could make a PR if one of the maintainers agrees with this change :)

Thanks for this great module!

**Comment by onmax** [comment]
I could also add a new test for Nested CSS [here](https://github.com/nuxt/fonts/blob/9ae5780e4271bf2ad03f511c43d2ab5f600a7e24/test/parse.test.ts#L139)

**Comment by danielroe** [comment]
that would be great - thank you 🙏
