### ISSUE TITLE
Support for custom Google Fonts baseUrl

### ISSUE THREAD

**Issue by qwerzl** [nuxt/fonts#40]
It would be nice to offer to customize `baseUrl` for Google Fonts provider in the config. My use case is that there's a high latency to Google Fonts in China, so many of us use mirrors.

**Comment by danielroe** [comment]
Would you give me an example of such a mirror? We fetch from two locations at the moment:

* https://fonts.google.com/metadata/fonts
* https://fonts.googleapis.com/css2

**Comment by qwerzl** [comment]
Sure, here's an example: https://mirror.sjtu.edu.cn/docs/google-fonts. They are mainly in Chinese.

However, as I've investigated more, looks like all the mirrors only provide reverse proxy to `fonts.googleapis.com`, but what really causes the connection issue is the request to `fonts.google.com`. So the only solution to the problem is to use the `local` provider.

**Comment by qwerzl** [comment]
That's also a good idea. I'll try it.
