### ISSUE TITLE
DevTools appends duplicate fonts on HMR change

### ISSUE THREAD

**Issue by rijkvanzanten** [nuxt/fonts#400]
Every HMR change of `nuxi dev`, the DevTools for fonts appends a new duplicate of the font files in use. No changes are made elsewhere

https://github.com/user-attachments/assets/896de0e7-28f0-4c05-9b5e-3b872db73d7c

This is an effectively empty new Nuxt project, using the `local` provider.

[Here's the project that's behaving this way](https://github.com/rijkvanzanten/rijk.nyc/tree/91689ef67f66a67a2cbb4c492c37d81d39f378f8). Outside of `eslint` being installed it's an empty new Nuxt 3 project so can be used as a minimal reproduction.

**Comment by arashsheyda** [comment]
I think [this line](https://github.com/nuxt/fonts/blob/3c633ddd05d0080b2945fc1db243a68dd365157b/src/devtools.ts#L84) is causing the issue

**Comment by rijkvanzanten** [comment]
Thanks for the tip @arashsheyda! 

Problem here is indeed that the `fonts` variable might already contain the font that's passed into the function when HMR runs. I'm not too familiar with the flow of data here, so not entirely sure if my solution is correct, but I'll open a PR in a sec here that checks if the font already exists in the 'loaded fonts' array before putting it in again and broadcasting it.
