### ISSUE TITLE
Docs (useage): TailwindCSS v4

### ISSUE THREAD

**Issue by waynegibson** [nuxt/fonts#409]
TailwindCSS v4 had an update to the way you configure theme fonts variables.  See this pull request https://github.com/tailwindlabs/tailwindcss/pull/14885.

The font family variable has been renamed from  --font-family-* variables to --font-*

Old way 
 ```
@theme {
  --font-family-display: "Inter", "sans-serif";
}
```
New way
```
@theme {
  --font-display: "Inter", "sans-serif";
}
```

**Comment by danielroe** [comment]
thank you for this! ❤
