### ISSUE TITLE
Could not initialize provider googleicons. unifont will not be able to process fonts provided by this provider. fetch failed

### ISSUE THREAD

**Issue by Buringcarbon** [nuxt/fonts#424]
Each time the project is restarted or changed, the following error occurs:

 WARN  Could not fetch from https://fonts.google.com/metadata/icons?key=material_symbols&incomplete=true. Will retry in 1000ms. 3 retries left.                                                                           19:30:58  

 WARN  Could not fetch from https://fonts.google.com/metadata/icons?key=material_symbols&incomplete=true. Will retry in 1000ms. 2 retries left.                                                                           19:31:09  

 WARN  Could not fetch from https://fonts.google.com/metadata/icons?key=material_symbols&incomplete=true. Will retry in 1000ms. 1 retries left.                                                                           19:31:20  

 ERROR  Could not initialize provider googleicons. unifont will not be able to process fonts provided by this provider. fetch failed 
 ERROR  Could not initialize provider googleicons. unifont will not be able to process fonts provided by this provider. fetch failed

**Comment by yellinzero** [comment]
@Buringcarbon Hi, sorry to bother you. How did you solve this problem? I’ve encountered it as well.

**Comment by urbgimtam** [comment]
I'm experiencing the same right now. Can you share what happened and how you solved it, please?

**Comment by rtabulov** [comment]
@urbgimtam @Buringcarbon did you resolve the issue? i am facing the same error on a fresh project

**Comment by kingwrcy** [comment]
Same here.
How to resolve this issue? Why is closed as completed??

**Comment by urbgimtam** [comment]
I've started using bunny fonts instead, solved all issues. (bunny uses the same fonts as google, so a nice replacement).

**Comment by anoyah** [comment]
Same error right now, how to resolve this issus?

**Comment by hphunhundaodi** [comment]
export default defineNuxtConfig({
  compatibilityDate: '2025-07-15',
  devtools: { enabled: true },

  modules: [
    '@nuxt/content',
    '@nuxt/eslint',
    '@nuxt/image',
    '@nuxt/scripts',
    '@nuxt/test-utils',
    '@nuxt/ui'
  ],

  // set the provider to 'bunny', do not use default 'google'
  fonts: {
    provider: 'bunny'
  }
})
