### ISSUE TITLE
`google` is not recognised as a font provider

### ISSUE THREAD

**Issue by cybercoder-naj** [nuxt/fonts#438]
In my project, `google` is not recognised as a font provider even when the font exists on [google font](https://fonts.google.com/specimen/Archivo). Here is the configuration and the output:

```ts
export default defineNuxtConfig({
  fonts: {
    families: [
      { name: 'Archivo', provider: 'google' },
      { name: 'My Font', provider: 'local' }
    ]
  },
})
```

![Image](https://github.com/user-attachments/assets/3ea7f765-91fd-4520-a0ad-7c9198fbdc00)

Additionally, the code example playground [here](https://stackblitz.com/github/nuxt/fonts/tree/main/playground?file=package.json) from the docs has a different but potentially similar issue where the font providers aren't being initialised. 

![Image](https://github.com/user-attachments/assets/77be8524-bc93-483a-b5bf-771cb3822db3)

**Comment by danielroe** [comment]
The stackblitz issue is a CORS issue - unfortunately Nuxt Fonts doesn't really work in Stackblitz as there's no actual Node server involved.

Could you provide a reproduction? 🙏

**Comment by cybercoder-naj** [comment]
The error seems to be fixed automatically on our systems. I'll reopen if it opens up again thanks!
