### ISSUE TITLE
feat: fontsource provider

### ISSUE THREAD

**Issue by qwerzl** [nuxt/fonts#65]
I've explored other font providers, looks like `fontsource` is also quite promising.

Currently most of its fonts are from Google Fonts, along with some icons and some other fonts. It's also the service that Cloudflare Fonts is fetching from.

@danielroe Would you like to include this font provider? If so, I'd like to work on it.

Docs: https://fontsource.org/docs

**Comment by danielroe** [comment]
I would love that! It's a bit trickier because of the distribution method but ideas welcome! 🙏
